import requests
import json

msg = "打卡成功"
dingtalk_token = 'xxx'
dingtalk_url = 'https://oapi.dingtalk.com/robot/send?access_token='+dingtalk_token
data = {
    "msgtype": "text",
    "text": {
        "content": msg
    },
    "at": {
        "isAtAll": False
    }
}
headers = {'Content-Type': 'application/json'}
r = requests.post(dingtalk_url, data=json.dumps(data), headers=headers).json()
print(r)
